### ISSUE TITLE
label标签的文字与输入框的对齐问题

### ISSUE THREAD

**Issue by lwy1010** [lwy1010/Mr.0.2#12]
表单常见现象，label 标签文字里文字没对齐：

![1902051](https://github.com/lwy1010/mdHosting/blob/master/1902051.JPG?raw=true)

那就对齐就好了：

HTML:

```html
<form action="#" method="post">
    <div>
        <label for="name">用户名：</label>
        <input type="text" name="username" id="name" required />
    </div>
    <div>
        <label for="email">邮箱：</label>
        <input type="email" name="email" id="email" required />
    </div>
    <div>
        <label for="msg">反馈：</label>
        <textarea name="message" id="msg" cols="30" rows="10"></textarea>
    </div>
</form>
```

CSS:

```css
label {
    display: inline-block;
    width: 100px;
    text-align: right;
}
form div + div {
    margin-top: 1em;
}
textarea {
    /* 行内元素垂直对齐方式 */
    vertical-align: top;
    height: 10em;
}
```
